{% set version = "0.14.2" %}

package:
  name: dask
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 19b03af017f11396f727fbd21c3e5377098e7ae71362bf7a61be2eaf05fb9371

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - numpy
    - pandas >=0.19.0
    - partd >=0.3.7
    - toolz >=0.7.2
    - distributed >=1.16.0

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  summary: 'Parallel PyData with task scheduling'

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - koverholt
    - alimanfoo
    - martindurant
    - pitrou
    - tomaugspurger
