{% set version = "2021.9.1" %}

package:
  name: dask
  version: {{ version }}

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: e11f2bf2cac809e5408fc107dcf727af3bc3472160f206cb4b828211396ad65c

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7

  run:
    - python >=3.7
    - dask-core {{ version }}
    - distributed {{ version }}
    - cytoolz >=0.8.2
    - numpy >=1.18
    - pandas >=1.0
    - bokeh >=1.0.0,!=2.0.0
    - jinja2

  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

about:
  home: https://dask.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Parallel PyData with Task Scheduling
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
