{% set version = "2022.2.1" %}
{% set build_number = 0 %}


package:
  name: dask
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
    sha256: b699da18d147da84c6c0be26d724dc1ec384960bf1f23c8db4f90740c9ac0a89
    folder: dask
  - url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
    sha256: fb62a75af8ef33bbe1aa80a68c01a33a93c1cd5a332dd017ab44955bf7ecf65b
    folder: distributed

build:
  number: {{ build_number }}

outputs:
  - name: dask-core
    build:
      noarch: python
      number: {{ build_number }}
    script: build-dask-core.sh
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - cloudpickle >=1.1.1
        - fsspec >=0.6.0
        - packaging >=20.0
        - partd >=0.3.10
        - pyyaml >=5.3.1
        - toolz >=0.8.2
      run_constrained:
        - cytoolz >=0.8.2
        - numpy >=1.18
        - pandas >=1.0
        - distributed {{ version }}
        - bokeh >=2.1.1
        - jinja2
    test:
      requires:
        - pip
      imports:
        - dask
      commands:
        - python -m pip check
    about:
      home: https://dask.org/
      summary: Parallel PyData with Task Scheduling
      license: BSD-3-Clause
      license_file: dask/LICENSE.txt
      doc_url: https://dask.org/
      dev_url: https://github.com/dask/dask

  - name: distributed
    version: {{ version }}
    build:
      noarch: python
      number: {{ build_number }}
    script: build-distributed.sh
    entry_points:
      - dask-scheduler = distributed.cli.dask_scheduler:go
      - dask-ssh = distributed.cli.dask_ssh:go
      - dask-worker = distributed.cli.dask_worker:go
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - click >=6.6
        - cloudpickle >=1.5.0
        - cytoolz >=0.8.2
        - dask-core {{ version }}
        - jinja2
        - msgpack-python >=0.6.0
        - packaging >=20.0
        - psutil >=5.0
        - pyyaml
        - sortedcontainers !=2.0.0,!=2.0.1
        - tblib >=1.6.0
        - toolz >=0.8.2
        - tornado >=6.0.3
        - zict >=0.1.3
        - setuptools <60.0.0
      run_constrained:
        - openssl !=1.1.1e
    test:
      requires:
        - pip
      imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
      commands:
        - python -m pip check
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    about:
      home: https://distributed.dask.org
      summary: Distributed scheduler for Dask
      license: BSD-3-Clause
      license_family: BSD
      license_file: distributed/LICENSE.txt
      description: |
        Distributed is a lightweight library for distributed computing in Python.
        It extends both the concurrent.futures and dask APIs to moderate sized
        clusters.
      doc_url: https://distributed.dask.org
      doc_source_url: https://github.com/dask/distributed/blob/main/docs/source/index.rst
      dev_url: https://github.com/dask/distributed

  - name: dask
    version: {{ version }}
    build:
      noarch: python
      number: {{ build_number }}
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - dask-core {{ version }}
        - distributed {{ version }}
        - cytoolz
        - numpy
        - pandas
        - bokeh
        - jinja2
    test:
      imports:
        - dask
        - dask.array
        - dask.bag
        - dask.bytes
        - dask.dataframe
        - dask.dataframe.tseries
        - dask.delayed
        - dask.diagnostics
        - dask.distributed
        - distributed
    about:
      home: https://dask.org/
      summary: Parallel PyData with Task Scheduling
      license: BSD-3-Clause
      license_file: dask/LICENSE.txt
      description: |
        Dask is a flexible parallel computing library for analytics.
      doc_url: https://dask.org/
      dev_url: https://github.com/dask/dask

about:
  home: https://dask.org/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file: dask/LICENSE.txt
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - jrbourbeau
    - koverholt
    - marcelotrevisani
    - martindurant
    - mrocklin
    - ogrisel
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
