{% set version = "2025.1.0" %}
{% set python_min = "3.10" %}


package:
  name: dask
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: bb807586ff20f0f59f3d36fe34eb4a95f75a1aae2a775b521de6dd53727d2063

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - dask-core {{ version }}
    - distributed {{ version }}
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('dask-core', max_pin='x.x.x') }}
    - {{ pin_compatible('distributed', max_pin='x.x.x') }}
    - cytoolz >=0.11.0
    - lz4 >=4.3.2
    - numpy >=1.24
    - pandas >=2.0
    - bokeh >=3.1.0
    - jinja2 >=2.10.3
    - pyarrow >=14.0.1

  run_constrained:
    - openssl !=1.1.1e

test:
  requires:
    - python {{ python_min }}
    - pip

  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

  commands:
    - pip check
    - dask --version
    - dask info versions

about:
  home: https://dask.org/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - charlesbluca
    - alimanfoo
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
    - fjetter
