{% set version = "2024.10.0" %}


package:
  name: dask
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: dfd3efec5d8d8340fb647d0347637133030cad261b714623cc27de286e9db037

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - dask-core {{ version }}
    - distributed {{ version }}
  run:
    - python >=3.10
    - {{ pin_compatible('dask-core', max_pin='x.x.x') }}
    - {{ pin_compatible('distributed', max_pin='x.x.x') }}
    - cytoolz >=0.11.0
    - lz4 >=4.3.2
    - numpy >=1.24
    - pandas >=2.0
    - dask-expr >=1.1,<1.2
    - bokeh >=3.1.0
    - jinja2 >=2.10.3
    - pyarrow >=14.0.1

  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

  commands:
    - dask --version
    - dask info versions

about:
  home: https://dask.org/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - charlesbluca
    - alimanfoo
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - jrbourbeau
    - fjetter
