{% set version = "1.1.5" %}

package:
  name: dask
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 4b0b82a4d61714d3a49953274b1a8a689a51eacf89c4c2ff18aa7f6282ce515e

build:
  number: 0
  noarch: python

requirements:
  build:
    - python

  run:
    - python
    - bokeh >=0.13.0
    - cloudpickle >=0.2.1
    - cytoolz >=0.7.3
    - dask-core {{ version }}
    - distributed >=1.26.0
    - numpy >=1.11.0
    - pandas >=0.19.0
    - partd >=0.3.8
    - toolz >=0.7.3

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.distributed
    - distributed

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Parallel Python with task scheduling'
  doc_url: https://dask.pydata.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jcrist
    - koverholt
    - martindurant
    - mrocklin
    - pitrou
    - tomaugspurger
    - shoyer
